// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: cheaters_query.sql

package repo

import (
	"context"
)

const insertNewCheater = `-- name: InsertNewCheater :one
insert into cheaters (
	polaris_id, created_at, updated_at
) values ($1, $2, $3)
returning id, polaris_id, created_at, updated_at
`

type InsertNewCheaterParams struct {
	PolarisID string
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) InsertNewCheater(ctx context.Context, arg InsertNewCheaterParams) (Cheater, error) {
	row := q.db.QueryRow(ctx, insertNewCheater, arg.PolarisID, arg.CreatedAt, arg.UpdatedAt)
	var i Cheater
	err := row.Scan(
		&i.ID,
		&i.PolarisID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
