// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: evidences_query.sql

package repo

import (
	"context"
)

const insertNewEvidence = `-- name: InsertNewEvidence :one
insert into evidences (
	polaris_id, evidence_url, offence_category, created_at, updated_at
) values (
	$1, $2, $3, $4, $5
) returning id, polaris_id, evidence_url, offence_category, created_at, updated_at
`

type InsertNewEvidenceParams struct {
	PolarisID       string
	EvidenceUrl     string
	OffenceCategory string
	CreatedAt       int64
	UpdatedAt       int64
}

func (q *Queries) InsertNewEvidence(ctx context.Context, arg InsertNewEvidenceParams) (Evidence, error) {
	row := q.db.QueryRow(ctx, insertNewEvidence,
		arg.PolarisID,
		arg.EvidenceUrl,
		arg.OffenceCategory,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Evidence
	err := row.Scan(
		&i.ID,
		&i.PolarisID,
		&i.EvidenceUrl,
		&i.OffenceCategory,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
