// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Player struct {
	ID        int32
	PolarisID pgtype.Text
	Name      pgtype.Text
	Power     pgtype.Int4
	Rank      pgtype.Int4
	RegionID  pgtype.Int4
	CreatedAt pgtype.Int4
	UpdatedAt pgtype.Int4
}
