// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repo

type Player struct {
	ID        int32
	PolarisID string
	Name      string
	Rank      int32
	RegionID  int32
	CreatedAt int64
	UpdatedAt int64
}
