// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: players_query.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertNewPlayer = `-- name: InsertNewPlayer :one
insert into players (
	id, polaris_id, name, power, rank, region_id, created_at, updated_at
) values (
	$1, $2,	$3, $4,	$5, $6, $7, $8
)
returning id, polaris_id, name, power, rank, region_id, created_at, updated_at
`

type InsertNewPlayerParams struct {
	ID        int32
	PolarisID pgtype.Text
	Name      pgtype.Text
	Power     pgtype.Int4
	Rank      pgtype.Int4
	RegionID  pgtype.Int4
	CreatedAt pgtype.Int4
	UpdatedAt pgtype.Int4
}

func (q *Queries) InsertNewPlayer(ctx context.Context, arg InsertNewPlayerParams) (Player, error) {
	row := q.db.QueryRow(ctx, insertNewPlayer,
		arg.ID,
		arg.PolarisID,
		arg.Name,
		arg.Power,
		arg.Rank,
		arg.RegionID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.PolarisID,
		&i.Name,
		&i.Power,
		&i.Rank,
		&i.RegionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
