// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: players_query.sql

package repo

import (
	"context"
)

const insertNewPlayer = `-- name: InsertNewPlayer :one
insert into players (
	polaris_id, name, power, rank, region_id, chara_id, created_at, updated_at
) values (
	$1,	$2, $3,	$4, $5, $6, $7, $8
)
returning id, polaris_id, name, power, rank, chara_id, region_id, created_at, updated_at
`

type InsertNewPlayerParams struct {
	PolarisID string
	Name      string
	Power     int32
	Rank      int32
	RegionID  int32
	CharaID   int32
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) InsertNewPlayer(ctx context.Context, arg InsertNewPlayerParams) (Player, error) {
	row := q.db.QueryRow(ctx, insertNewPlayer,
		arg.PolarisID,
		arg.Name,
		arg.Power,
		arg.Rank,
		arg.RegionID,
		arg.CharaID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.PolarisID,
		&i.Name,
		&i.Power,
		&i.Rank,
		&i.CharaID,
		&i.RegionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
